---

- name: "Gathering facts"
  setup:
    gather_subset: network

- name: "Register a cluster id"
  shell: /opt/1C/v8.3/x86_64/rac cluster list | grep ^cluster | awk '{print $3}'
  register: result

- name: "Set userparameter config for 1c server"
  template:
      dest: /etc/zabbix/zabbix_agentd.d/1c-agent.conf
      src: zabbix/zabbix_agentd.d/1c-agent.conf.j2

- name: "Get ip and hostname monitoring server"
  set_fact:
      key_value: host_monitor
  loop: "{{ groups['ERC_MONITORING-servers'] }}"
  register: host_monitor

- name: "Register the host in zabbix inventory"
  local_action:
    module: zabbix_host
    server_url: "{{zabbix_url}}"
    login_user: "{{zabbix_admin_user}}"
    login_password: "{{users.zabbix_admin_password}}"
    state: present
    host_name: "{{ inventory_hostname }}"
    visible_name: "{{ inventory_hostname }}"
    inventory_mode: automatic
    interfaces: "{{ zabbix_agent_interfaces }}"
    link_templates: 
      - Template OS Linux
      - 1CServices_health
    status: enabled
    host_groups: "{{ group_names }}"
  register: hostregister  

- name: Restart service zabbix_agent 
  service:
      name: "{{ zabbix_agent_service }}"
      state: restarted
  when: hostregister.changed    
