
- name: "Create zabbix host groups"
  local_action:
    module: zabbix_group
    server_url: "{{ zabbix_url }}"
    login_user: "{{zabbix_admin_user}}"
    login_password: "{{users.zabbix_admin_password}}"
    state: present
    host_groups: "{{ zabbix_host_groups }}"